app:
  message: "This is the DEV message."

#Security as Resources Server Configuration
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Wasl

#MySql Database connection configuration
  datasource:
    url: jdbc:mysql://localhost:3306/walsdb
    username: root
    password: root123

#Database ConnectionPoll configuration
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1800000 # 30 minutes
      leak-detection-threshold: 2000 # 2 seconds (good for dev, might disable in prod)
      pool-name: WaslHikariPool

#Database Migration configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    baseline-version: 1
    clean-disabled: true

#Jpa configration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

#Keycloak Adming Configuration
keycloak:
  admin:
    client-id: admin-cli  # Separate admin client
    client-secret: cXshahPtEeXQfVHjUpJtb2XbwdMN2jXX
    server-url: http://localhost:8081
    realm: Wasl  # For admin operations

#VideoStream platform secrete key
Stream:
  secret-key: 7sekgqgyy2caykep8nwf4fstzjmk4ttst3h9byzgg3w4uwmmgdwxkrqmcdhk6sxj


