
ALTER TABLE meeting_invitations
MODIFY COLUMN status ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'JOINED')
NOT NULL DEFAULT 'PENDING';


ALTER TABLE notifications
MODIFY COLUMN type ENUM('INVITATION', 'RESPONSE', 'PERSONAL_IMMEDIATE');
